pipeline {

    agent any

    environment {

        IMAGE_NAME = "hello-jenkins-app-docker-integration"

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Build Application') {

            steps {
                dir('sonarqube'){

                sh "./mvnw clean package"

                }
            }

        }

        stage('SonarQube Analysis') {

            steps {

                dir('sonarqube'){
                    withSonarQubeEnv('SonarQube') {
                        
                        sh """
                            ./mvnw clean verify sonar:sonar \
                            -Dsonar.token=${SONAR_AUTH_TOKEN}
                        """
                    }

                }

            }

}
        

        stage('Build Docker Image') {

            steps {

                dir('sonarqube'){

                sh """
                    docker build \
                    -t ${IMAGE_NAME}:${IMAGE_TAG} \
                    .
                """

            }
            }

        }

        stage('List Docker Images') {

            steps {

                sh "docker images"

            }

        }

    }

}